version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app

jobs:
  run-docker:
    executor: docker-executor
    parameters:
      run_id:
        type: string
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.24

      - run:
          name: Pull Docker images
          command: |
            docker pull nduythanh1/selenium-chrome-app
            docker pull nduythanh1/stream-app
            docker pull nduythanh1/selenium-earnvids-app
    


      - run:
          name: Run 5 containers in parallel (hard limit 15 minutes)
          command: |
            timeout 15m bash -c '
              echo "🚀 Starting 5 containers in parallel for RUN_ID: << parameters.run_id >>"
      
              timeout 15m docker run --rm -e RUN_ID=<< parameters.run_id >>_a nduythanh1/stream-app > stream1_<< parameters.run_id >>.log 2>&1 &
              timeout 15m docker run --rm -e RUN_ID=<< parameters.run_id >>_b nduythanh1/stream-app > stream2_<< parameters.run_id >>.log 2>&1 &
              timeout 15m docker run --rm -e RUN_ID=<< parameters.run_id >>_c nduythanh1/selenium-earnvids-app > earn1_<< parameters.run_id >>.log 2>&1 &
              timeout 15m docker run --rm -e RUN_ID=<< parameters.run_id >>_d nduythanh1/selenium-earnvids-app > earn2_<< parameters.run_id >>.log 2>&1 &
              timeout 15m docker run --rm -e RUN_ID=<< parameters.run_id >>_e nduythanh1/selenium-chrome-app > chrome_<< parameters.run_id >>.log 2>&1 &
      
              wait
              echo "✅ All 5 containers completed (or timed out) for RUN_ID: << parameters.run_id >>"
            '
      
workflows:
  run-parallel:
    jobs:
      - run-docker:
          matrix:
            parameters:
              run_id: ["job1", "job2", "job3", "job4", "job5", "job6","job7", "job8", "job9", "job10",
                       "job11", "job12", "job13", "job14", "job15", "job16","job17", "job18", "job19", "job20",
                       "job21", "job22", "job23", "job24", "job25", "job26","job27", "job28", "job29", "job30"]
